### ISSUE TITLE
是否考虑写到数据库？

### ISSUE THREAD

**Issue by zhanpengguo** [qqxx6661/log-record#10]
一些简单项目不依赖消息队列和springcloud，能否直接写到数据库

**Comment by qqxx6661** [comment]
>=1.1.0以上的版本，支持本地直接处理消息。


若只需要在同一应用内处理日志信息，只需要实现接口IOperationLogGetService，便可对日志进行处理。

比如落库都是直接处理的，我现在自己用也是拿到消息后直接落表。

```
public class CustomFuncTestOperationLogGetService implements IOperationLogGetService {
    @Override
    public void createLog(LogDTO logDTO) {
        log.info("logDTO: [{}]", JSON.toJSONString(logDTO));
    }
}
```

并且其他几个消息队列，管道，都是非强制依赖的，maven也都是optional引入，所以整体还是很轻量化的。
