### ISSUE TITLE
@OperationLog的success参数建议

### ISSUE THREAD

**Issue by Bolin-Sun** [qqxx6661/log-record#102]
我有个问题
**```@OperationLog``` 这个注解有个success() 的参数 可以判断函数是否执行成功，文档如下图**
- ![image](https://github.com/qqxx6661/log-record/assets/57434554/a8d0c2de-b88f-42e5-a1f9-a42e14b7c07e)
**因为我这个项目是已完成的项目，返回的参数都是统一的，如下图**
- ![image](https://github.com/qqxx6661/log-record/assets/57434554/fba27833-39ac-4fe2-a02b-6a1a83ed9ca8)

**这样操作的话就侵入了业务逻辑。而且要改很多的接口，我就是想能不能出个接口，让我自己来根据方法的返回参数判断接口是否执行成功，如果方法执行抛出了错误那么自动认为方法执行失败了**

**Comment by qqxx6661** [comment]
success字段也是支持SpEL表达式的，你上面贴的代码，只要在注解的success上写成类似下面的表达式

@OperationLog(success="#_return.code==0", // 其他注解字段省略)

就能拿到你返回值的code字段。

文档里有”内置自定义函数和自定义参数“一节可以看下
