### ISSUE TITLE
LogRecordFunc 注解是否只支持标注static方法

### ISSUE THREAD

**Issue by LionSiHan** [qqxx6661/log-record#23]
大多情况下自定义的函数为了查old的值都会调用spring容器中的方法去获取，在@Component注解标记的类中使用LogRecordFunc注解会报空指针,代理类获取不到Annotation,微调后发现非静态方法无法放到StandardEvaluationContext里

**Comment by qqxx6661** [comment]
是的，只支持static方法，这是由SpEL的特性决定的。

有几个方法解决：

1. 无侵入方式：使用SpringContextUtils.getBean(TestService.class)在静态方法中调用服务

```
@LogRecordFunc("CustomFuctionClass")
public class CustomFuctionClass {

    private static TestService testService;

    @LogRecordFunc
    public static String customFunction(String str) {
        if (testService == null) {
            testService = SpringContextUtils.getBean(TestService.class);
        }
        return testService.testServiceFunc2(str);
    }
}
```

可以参考我为本仓库准备的Demo工程：

https://github.com/monitor4all/systemLog/blob/main/logRecordWebDemo/src/main/java/cn/monitor4all/logrecordwebdemo/function/CustomFuctionClass.java

2. 有侵入方式：使用LogRecordContext.put(oldValue)在业务代码中查询并传递旧值，在LogRecordContext里的变量也可以直接使用#oldValue类似的变量名参与SpEL运算

其他方式暂时没有想到，但是不排除会有更好的方式。
