### ISSUE TITLE
推荐项目命名成`log-record`，更常用的业界命名风格

### ISSUE THREAD

**Issue by oldratlee** [qqxx6661/log-record#26]
https://github.com/qqxx6661/logRecord -> `log-record`

项目命名示例：

- https://github.com/spring-projects/spring-framework
- https://github.com/spring-projects/spring-boot
- https://github.com/alibaba/transmittable-thread-local

**Comment by qqxx6661** [comment]
嗯，可以的。之后还准备挂到企业下面，现在个人名字下面也有点尴尬。

**Comment by oldratlee** [comment]
看起来，命名风格与是否挂在个人名字正交 ❤️

**Comment by qqxx6661** [comment]
> 看起来，命名风格与是否挂在个人名字正交 ❤️

说的没错 :)
