### ISSUE TITLE
批量操作是如何支持的？

### ISSUE THREAD

**Issue by jinyang-git-hub** [qqxx6661/log-record#47]
针对业务中的批量操作，比如批量删除、批量新增操作，通过注解的方式记录日志时貌似无法满足业务需求，请问您这种情况有考虑吗？

**Comment by qqxx6661** [comment]
我理解你说的批量应该是入参内一次性包含多条记录是吧？暂时没有支持批量操作。如果要用可以在外层方法使用循环来调用加了日志注解的方法。

这个需要考虑是否有必要，因为业务代码对于批量的设计可能五花八门。要抽象出一个通用的，合理的，支持批量的设计，还需要讨论。是否对业务层干涉过多也需要评估。

可以在此讨论。如果有完善的方案可以支持。
