### ISSUE TITLE
这个项目是美团技术博客上那篇文章的具体实现吗？

### ISSUE THREAD

**Issue by Wo1framalpha** [qqxx6661/log-record#6]
如题

**Comment by qqxx6661** [comment]
不是美团官方的实现，你可以理解为我们学习美团文章后自己的实现。

目前实现的功能没有美团文章介绍的那么全，不过基础功能都已经支持。


美团的暂时只在内部开源，尚未外部开源。


也欢迎加入一起开发。

**Comment by qqxx6661** [comment]
这个仓库实现了直接写入常用消息队列的支持，算是超出美团原文的一个feature

**Comment by Wo1framalpha** [comment]
> 不是美团官方的实现，你可以理解为我们学习美团文章后自己的实现。
> 
> 目前实现的功能没有美团文章介绍的那么全，不过基础功能都已经支持。
> 
> 
> 美团的暂时只在内部开源，尚未外部开源。
> 
> 
> 也欢迎加入一起开发。
> 
> 

明白了，美团那篇文章我一直很有兴趣，但囷于时间和能力，一直无从下手，感谢你们付出时间与精力做出了一个可供参考的实现。

在此还有一个小小的建议，考虑到README.md中直接引用了美团文章中的图片，为了避免引起不必要的争议，最好还是通过增加一个图注或其他方式标明一下来源，亦或是使用你们自己的图片将其替换。

**Comment by qqxx6661** [comment]
好的，晚点我修改一下，谢谢建议～

**Comment by GravityMatrix** [comment]
这个是美团文章作者

**Comment by qqxx6661** [comment]
> 这个是美团文章作者项目 https://github.com/mouzt/mzt-biz-log

感谢，我也正好学习学习，居然个人名义开源了。
