### ISSUE TITLE
Diff功能支持数组吗？

### ISSUE THREAD

**Issue by znicholas** [qqxx6661/log-record#69]
Diff功能支持数组吗？

**Comment by qqxx6661** [comment]
README中有，
> 注意：目前DIFF功能支持完全不同的类之间进行DIFF，对于同名的基础类型，进行equals对比，对于同名的非基础类型，则借用fastjson的toJSON能力，转为JSONObject进行对比，本质上是将对象映射为map进行map.equals。

所以数组可以支持，是将两个数组JSON化后进行对比。

**Comment by qqxx6661** [comment]
先关闭了，有进一步提问可以重开。
