### ISSUE TITLE
如何实现LogRecordContext.putGlobalVariable这个操作

### ISSUE THREAD

**Issue by PzTao** [qqxx6661/log-record#70]
LogRecordContext.putVariable其他方法获取不到,是否存在LogRecordContext.putGlobalVariable这种操作呢

**Comment by qqxx6661** [comment]
LogRecordContext是线程级别共享的。能否提供一下你的实际使用方式，确认下是不是跨线程使用了？

如果确实需要跨线程使用，目前的LogRecordContext是不支持的，目前正在使用TransmittableThreadLocal改造。

目前开放了 “日志处理线程池前置处理” 特性。在README中有提到，看下能否满足需求：

> 在使用线程池处理包装好的日志之前，很多人有一些特殊逻辑需要插入，比如将traceId放入上下文，这里开放接口在logDTO发送给线程池前允许加入用户自定义逻辑。
> 
> 使用方式如下，添加SpringBean覆写LogRecordThreadWrapper

```
@Slf4j
@Configuration
public class LogRecordConfig {

    @Bean
    public LogRecordThreadWrapper logRecordThreadWrapper() {
        return new LogRecordThreadWrapper() {
            @Override
            public Runnable createLog(Consumer<LogDTO> consumer, LogDTO logDTO) {
                log.info("Before send createLog task to LogRecordThreadPool. Current thread [{}]", Thread.currentThread().getName());
                return LogRecordThreadWrapper.super.createLog(consumer, logDTO);
            }
        };
    }

}
```

**Comment by PzTao** [comment]
> 

![1](https://user-images.githubusercontent.com/33417248/232447548-ae86742b-ac74-48b7-b37f-a2499c206d94.png)
![2](https://user-images.githubusercontent.com/33417248/232447574-7b9a3eb8-bee3-4fbe-8d67-c021710c59c8.png)
![3](https://user-images.githubusercontent.com/33417248/232447598-4935ba88-aabb-451c-bc47-d6c361a6f384.png)
当我在红框方法上使用 
`@OperationLog(bizId = "#bizId",bizType = "''",msg = "''")`
就会导致第三张图片处获取不到bizId,去掉则能正常获取

**Comment by qqxx6661** [comment]
> > 
> 
> ![1](https://user-images.githubusercontent.com/33417248/232447548-ae86742b-ac74-48b7-b37f-a2499c206d94.png) ![2](https://user-images.githubusercontent.com/33417248/232447574-7b9a3eb8-bee3-4fbe-8d67-c021710c59c8.png) ![3](https://user-images.githubusercontent.com/33417248/232447598-4935ba88-aabb-451c-bc47-d6c361a6f384.png) 当我在红框方法(第二张图)上使用 `@OperationLog(bizId = "#bizId",bizType = "''",msg = "''")` 就会导致第三张图片处获取不到bizId,去掉则能正常获取

putVariable写在哪里了？还是说你想拿的是注解上的bizId

**Comment by PzTao** [comment]
> > > 
> > 
> > 
> > ![1](https://user-images.githubusercontent.com/33417248/232447548-ae86742b-ac74-48b7-b37f-a2499c206d94.png) ![2](https://user-images.githubusercontent.com/33417248/232447574-7b9a3eb8-bee3-4fbe-8d67-c021710c59c8.png) ![3](https://user-images.githubusercontent.com/33417248/232447598-4935ba88-aabb-451c-bc47-d6c361a6f384.png) 当我在红框方法(第二张图)上使用 `@OperationLog(bizId = "#bizId",bizType = "''",msg = "''")` 就会导致第三张图片处获取不到bizId,去掉则能正常获取
> 
> putVariable写在哪里了？还是说你想拿的是注解上的bizId

放在了最外层,id里的bizId也是从LogRecordContext获取的
