### ISSUE TITLE
jdk17 & springboot3

### ISSUE THREAD

**Issue by mymx2** [qqxx6661/log-record#71]
支持jdk17 及 springboot3

javassist方法：

![image](https://user-images.githubusercontent.com/32814920/233836135-15c1408d-47d9-4925-a593-905a8722389b.png)

自动配置更改：

![image](https://user-images.githubusercontent.com/32814920/233836160-d89db72f-66b2-4384-b650-869e1e7953f9.png)

**Comment by qqxx6661** [comment]
OK，放在TODO List里后面改一下，也欢迎pr。其实DIFF中用到的JavaAssist我有想法把他们从新版本里删除掉，有点太hack了。

**Comment by mymx2** [comment]
> OK，放在TODO List里后面改一下，也欢迎pr。其实DIFF中用到的JavaAssist我有想法把他们从新版本里删除掉，有点太hack了。

去除吧，看用哪个diff包[https://github.com/search?o=desc&q=java-object-diff&s=stars&type=Repositories](https://github.com/search?o=desc&q=java-object-diff&s=stars&type=Repositories)

另外，在可doc中加个tip：项目中默认采用框架异步线程池，如需传递上下文环境（如requestId等），请将`log-record.thread-pool.enabled`改为false，自定义异步实现。

**Comment by qqxx6661** [comment]
从1.6.0版本开始支持springboot3(JDK17)

```
<dependency>
  <groupId>cn.monitor4all</groupId>
  <artifactId>log-record-springboot3-starter</artifactId>
  <version>1.6.0</version>
</dependency>
```

可以查看最新的README.md

https://github.com/qqxx6661/log-record/blob/v1.6.0/README.md

若有更多疑问可以重开issue
