### ISSUE TITLE
MQ支持Kafka吗

### ISSUE THREAD

**Issue by Oislop** [qqxx6661/log-record#72]
我看介绍支持RabbitMQ、RocketMQ、SpringCloud Stream。如果想接入其他MQ，有对应的扩展点嘛？

**Comment by qqxx6661** [comment]
目前对数据管道没开放扩展点，主要是各种消息队列抽象定义区别太大，我现在无法设计好。但现在有最通用的处理方式。可以见README文档，本地处理：

```
@Component
public class CustomFuncTestOperationLogGetService implements IOperationLogGetService {
    @Override
    public void createLog(LogDTO logDTO) {
        log.info("logDTO: [{}]", JSON.toJSONString(logDTO));
    }
}
```

**Comment by qqxx6661** [comment]
目前考虑仅通过IOperationLogGetService获取日志实体后由用户自行处理，包括对接其他MQ，这样做的目的是降低框架复杂度，不耦合过多后置处理逻辑（例如各种MQ，因为MQ配置繁多，很难对MQ保持持续兼容）
