### ISSUE TITLE
关于 Diff 根据内容忽略字段的建议

### ISSUE THREAD

**Issue by duanluan** [qqxx6661/log-record#76]
1. 只修改部分字段时，msg 显示了全部字段。
编辑接口使用 Diff，`msg`最终为：“【username】从【xxx】变成了【 】 【xxx】……”。实际上因为 MyBatis 配置的更新策略，是不会更新参数中为 null 的字段（此处即 username）的，但是操作日志中却显示了。
建议新增一个全局配置，用于 Diff 时忽略 newObj 中为 null 或为空或指定内容的字段。还可以给`@LogRecordDiffField`新增一个属性用于单独配置。
2. 感觉`@LogRecordDiffIgnoreField`这个注解，可以变成`@LogRecordDiffField`的一个属性。

关于第 1 点，我现在自己的做法是在`implements IOperationLogGetService`的类中判断`diffDTOList`是否不为空，如果不为空的话，获取其中 newValue 为 null 的，再去处理 msg。

**Comment by qqxx6661** [comment]
整理了一下诉求：
1. 新增全局配置：DIFF忽略源或目标为null的字段。
2. @LogRecordDiffField修改：新增独立忽略null的属性
3. @LogRecordDiffIgnoreField作为@LogRecordDiffField的属性

感觉3个都是很合理的改动，我争取尽快修改支持。

**Comment by duanluan** [comment]
请问有进展吗？

**Comment by qqxx6661** [comment]
> 请问有进展吗？

有的。昨天刚写完功能，还在写单元测试。今天争取给你打个SNAPSHOT包，过两天测完发正式版本

**Comment by qqxx6661** [comment]
1.5.1-SNAPSHOT 快照版本发布。

新的文档见分支代码里的README中DIFF一节
https://github.com/qqxx6661/log-record/blob/f78abf88d8ed897aa0828daa1841bd8c3c74326b/README.md

晚几天发正式版

**Comment by qqxx6661** [comment]
版本号 1.5.1
