### ISSUE TITLE
SystemLogAspect 中 原方法执行异常时的logDTOList 添加数据有问题

### ISSUE THREAD

**Issue by fish-liu** [qqxx6661/log-record#78]
// 原方法执行异常
        catch (Throwable throwable) {
            // 方法异常执行后日志切面
            try {
                if (stopWatch != null) {
                    stopWatch.stop();
                    executionTime = stopWatch.getTotalTimeMillis();
                }
                // 在LogRecordContext中写入执行后信息
                LogRecordContext.putVariable(LogRecordContext.CONTEXT_KEY_NAME_ERROR_MSG, throwable.getMessage());
                for (OperationLog annotation : annotations) {
                    if (!annotation.executeBeforeFunc()) {
                        logDtoMap.put(annotation, resolveExpress(annotation, pjp));
                    }
                }
                // 写入异常执行后日志
                logDTOList = new ArrayList<>(logDtoMap.values());
                logDTOList.forEach(logDTO -> {                                      //  此处的是否有问题？？
                    logDTO.setSuccess(false);
                    logDTO.setException(throwable.getMessage());
                });
            } catch (Throwable throwableAfterFuncFailure) {
                log.error("OperationLogAspect doAround after function failure, error:", throwableAfterFuncFailure);
            }
            // 抛出原方法异常
            throw throwable;
        } finally {

**Comment by qqxx6661** [comment]
具体说说？没看出来。

**Comment by fish-liu** [comment]
@Data
public class LogDTO {

    private boolean success;

    private String exception;

}


public class Test001 {

    public static void main(String[] args) {

        List<LogDTO> logDTOList = new ArrayList<>(3);
        System.out.println("------000-------" + logDTOList.size());
        logDTOList.forEach(logDTO -> {                                      //  此处的是否有问题？？
            logDTO.setSuccess(false);
            logDTO.setException("throwable.getMessage()");
            System.out.println("-------------");
        });
        System.out.println("------1111-------" + logDTOList.size());
        for(LogDTO logDTO : logDTOList){
            System.out.println("-------------"+logDTO.getException());
        }
    }

}

我的运行结果：
------000-------0
------1111-------0

Process finished with exit code 0

说明 logDTOList.forEach() 根本不会执行
是不是可以说finally 里面的 logDTOList.forEach()  也不会执行，也就是说原方法异常时，不会保存任何操作记录

**Comment by qqxx6661** [comment]
你注解@OperationLog一行具体是怎么写的？

我看你上方的代码， new ArrayList<>(3); 然后也没塞值给数组，前后都是0没问题吧。

**Comment by qqxx6661** [comment]
![image](https://github.com/qqxx6661/log-record/assets/12525295/b85e90af-565b-45ef-bc39-e862c50d199b)



看了下，我是用的java.util.ArrayList#ArrayList(java.util.Collection<? extends E>)构造方法，所以是塞了Map的value数组构造进去的。
你可以用这个单测case试下cn.monitor4all.logRecord.test.OperationLogNormalTest#testMethodThrowException

**Comment by fish-liu** [comment]
第一眼 看成是 logDTOList = new ArrayList<>(logDtoMap.size());  了，后面再看这段代码，惯性一直以为是logDtoMap.size() 
哈哈哈😆
