### ISSUE TITLE
Java17启动报错，改为jdk1.8就没问题

### ISSUE THREAD

**Issue by JohnnyLiQ** [qqxx6661/log-record#89]
![20231114165149](https://github.com/qqxx6661/log-record/assets/31117933/655c92dc-6f44-4d8e-8297-dded96b08ef2)

**Comment by JohnnyLiQ** [comment]
![Uploading 20231114165149.png…]()

**Comment by qqxx6661** [comment]
没兼容JDK17，晚点处理下

**Comment by qqxx6661** [comment]
从1.6.0版本开始支持springboot3(JDK17)

<dependency>
  <groupId>cn.monitor4all</groupId>
  <artifactId>log-record-springboot3-starter</artifactId>
  <version>1.6.0</version>
</dependency>

可以查看最新的README.md

https://github.com/qqxx6661/log-record/blob/v1.6.0/README.md

若有更多疑问可以重开issue
