### ISSUE TITLE
自定义上下文空字符串影响多个@OperationLog的定义顺序

### ISSUE THREAD

**Issue by itxingqing** [qqxx6661/log-record#96]
当自定义上下文中，设置一个为空字符串的值时，如LogRecordContext.putVariable("insertId", “”);
此时， @OperationLog注解有多个时间，顺序不会按照定义的顺序进行输出

**Comment by qqxx6661** [comment]
> @OperationLog注解有多个时间 

是指用了多个注解还是说有嵌套注解？能否把问题再详细描述下
