### ISSUE TITLE
编码文件格式问题

### ISSUE THREAD

**Issue by lionlinzq** [qqxx6661/log-record#98]
目前看代码是默认按照ISO-8859-1编码格式读取配置文件，但是这个似乎有问题，这种编码不支持配置中文？而且springboot之类的框架目前大多数也是默认按照utf-8来更改读取配置文件，所以目前自定义更改中文提示语是有问题的
![image](https://github.com/qqxx6661/log-record/assets/56428061/075066ac-d7d9-4600-b2e5-a08d463c5667)

**Comment by qqxx6661** [comment]
之前这块就发现有点问题但没有深究，之后有空看下。

**Comment by qqxx6661** [comment]
初步研究了下，目前大部分版本spring和springboot的application.properties默认都是ISO-8859-1。所以如果想要在配置里写中文，有两种方式：

- 使用方自行修改springboot的application.properties编码方式到UTF-8，这样可以直接在配置中写中文，比如：
  - 在自己的IDEA中更改编码方式。在setting中的File Encodings里修改配置文件编码方式至UTF-8
  - 通过设置spring.mandatory-file-encoding=UTF-8来要求应用程序必须使用UTF-8编码来读取配置文件。这个设置可以在application.properties文件或JVM启动参数中进行配置。
- 使用方无法修改或者不想修改application.properties到UTF-8编码，那么在ISO-8859-1下，想输入中文，使用方就需要将中文转为unicode格式后写在application.properties。上面你贴的图中，我的配置读取方式就是一种兼容方式(读取到的ISO-8859-1编码的字符串重新编码为UTF-8)。

实际上，还有一些方式能够绕过application.properties的默认编码方式，比如支持使用方通过环境变量或启动参数来设置这些配置，但是为了一个格式化配置设置在环境变量或者JVM参数里显得太过侵入性了。

貌似没找到更好的解决方案，能从我提供包的角度解决这个问题，你可以参考下。


参考：
https://umm.js.org/p/e678b765/
https://kucw.io/blog/2021/7/spring-chinese-properties/
